# Generated by Django 2.2.16 on 2022-11-23 20:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20221123_2333'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='check_author'),
        ),
    ]
